language: node_js

node_js: stable

install:
  - npm install -g hexo-cli
  - npm install

before_script:
  - git config user.name "volc"
  - git config user.email "liucannn@sina.com"
  - git clone https://github.com/volcanoliuc/hexo-theme-yilia.git themes/yilla
  - sed -i'' "s~https://github.com~https://${GITHUB_ACCESS_TOKEN}@github.com~" _config.yml
script:
  - hexo clean
  - hexo generate

after_success:
  - hexo deploy

branches:
  only:
    - master

