language: node_js
node_js: --lts
before_script:
  - git config user.name "jiu_ge"
  - git config user.email "liucannn@sina.com"
  - sed -i'' "s~https://github.com/volcanoliuc/blog.git~https://${GITHUB_ACCESS_TOKEN}@github.com/volcanoliuc/blog.git~" _config.yml
script:
  - hexo g
  - hexo d