language: node_js

node_js: stable

install:
  - npm install -g hexo-cli
  - npm install

before_script:
  - git config user.email "liucannn@sina.com"
  - sed -i'' "s~https://github.com~https://${GITHUB_ACCESS_TOKEN}@github.com~" _config.yml
script:
  - hexo clean
  - hexo g

after_success:
  - hexo d

branches:
  only:
    - master

