language: node_js

node_js: stable

install:
  - npm install -g hexo-cli
  - npm install

# before_script:
#   - git config user.email "liucannn@sina.com"
#   - sed -i'' "s~https://github.com/volcanoliuc/volcanoliuc.github.io.git~https://${GITHUB_ACCESS_TOKEN}@github.com/volcanoliuc/volcanoliuc.github.io.git~" _config.yml
script:
  - hexo clean
  - hexo g
after_script:
    - git clone https://${GH_REF} .deploy_git
    - cd .deploy_git
    - git checkout master
    - cd ../
    - mv .deploy_git/.git/ ./public/
    - cd ./public
    - git config user.name "volc"
    - git config user.email "liucannn@sina.com"
    - git add .
    - git commit -m "Travis CI Auto Builder"
    - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - master

env:
    global:
        - GH_REF: github.com/volcanoliuc/volcanoliuc.github.io.git

